### ISSUE TITLE
What theme?

### ISSUE THREAD

**Issue by lukeholder** [Zabanaa/zabanaa.github.io#2]
Are you using a theme or custom design for you blog? Looks great.

**Comment by TheanosLearning** [comment]
Amazing blog design. I came across it on Hacker News.

**Comment by willwillems** [comment]
I asume it's a custom design? Just stopping by here too to say it looks amazing

**Comment by Zabanaa** [comment]
Hi Guys,
Yeah it's a custom design that I worked on with a friend of mine who's a designer
I'm glad you like it 
Thanks for the feedback :smile: :smile:

**Comment by askz** [comment]
It looks like the github's Hacker theme a lil bit :)

https://pages-themes.github.io/hacker/
